nordektest:
  name: nordektest
  chainId: 58875
  domainId: 58875
  protocol: ethereum
  rpcUrls:
    - http: https://testnet-rpc.nordekscan.com/
  nativeToken:
    name: NRK
    symbol: NRK
    decimals: 18
linea:
  name: linea
  chainId: 59141
  domainId: 59141
  protocol: ethereum
  rpcUrls:
    - http: https://rpc.sepolia.linea.build

